# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5deed17f14ec7e1cb61a4f4903b12fc0270fc914df033b5fbf9c8be78a05074db8612f46e32fa39ec373afdeb991712222afcea9b697f849ca3e8daa91e8ea82

test:
  secret_key_base: e4009d3eee4616b83b0bc8e7081b9b86629f606df5d14d2bbead3be0bd2dc839ca847603e3080f0112cc84676b3a16efefd0fdb047b03197dff7d0ba4c645fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
